apiVersion: v1
kind: Service
metadata:
  name: realstate-app-service
  namespace: prod
  labels:
    env: prod
spec:
  type: ClusterIP
  selector:
      app: realstate
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP

