apiVersion: v1
kind: Service
metadata:
  name: login-app-service
  namespace: prod
  labels:
    env: prod
spec:
  type: ClusterIP
  selector:
    app: login
  ports:
    - targetPort: 8080
      port: 80
      protocol: TCP
    

