apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app-deployment
  namespace: prod
  labels:
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: mylogin-app
          image: tawfeeq421/login
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 150m
              memory: 120Mi
            limits:
              cpu: 300m
              memory: 240Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5


